routes/web.php
<?php

use App\Http\Controllers\AnnonceController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::resource("annonce", AnnonceController::class);

app/Models/Annonce.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Annonce extends Model
{
    use HasFactory;
    protected $guarded=[];
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/AnnonceController.php
<?php

namespace App\Http\Controllers;

use App\Models\Annonce;
use App\Http\Requests\AnnonceRequest;
use Illuminate\Http\Request;

class AnnonceController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $annonces=Annonce::all();
       return view("annonces.index", compact("annonces"));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view("annonces.create");
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(AnnonceRequest $request)
    {
        Annonce::create(
            [
                "titre"=>$request->titre,
                "description"=>$request->description,
                "type"=>$request->type,
                "neuf"=>$request->neuf,
                "ville"=>$request->ville,
                "superficie"=>$request->superficie,
                "prix"=>$request->prix,
            ]
        );
        return redirect()->route("annonce.index")->with("success", "la nouvelle annonce a été bien ajouté!");
    }

    /**
     * Display the specified resource.
     */
    public function show(Annonce $annonce)
    {
       return view("annonces.show", compact("annonce"));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Annonce $annonce)
    {
        return view("annonces.edit" , compact("annonce"));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Annonce $annonce)
    {
        $request->validate( [
         "titre"=> "required|unique:annonces,titre,".$annonce->id
        ]);

            $annonce->update($request->all());
         return redirect()->route("annonce.index")->with("success", "L'annonce a été mise à jour!");
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Annonce $annonce)
    {
       $annonce->delete();
       return redirect()->route("annonce.index")->with("success", "L'annonce a été supprimé!");

    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

resources/views/annonces/create.blade.php
@extends("templates.master")
@section("titre", "Nouvelle annonce")
@section("contenu")
      <h1 class="mt-2 mb-2">Nouvelle annonce</h1>   

    <form method="post" action="{{ route('annonce.store')}}"  class="w-50">
        @csrf
        <div class="mb-3">
        <label for="titre" class="form-label">Titre</label>
        <input type="text" class="form-control" id="titre" name="titre">
        </div>

        <div class="mb-3">
        <label for="description" class="form-label">Description</label>
        <input type="text" class="form-control" id="description" name="description">
        </div>

    
      
        <div class="mb-3">
        <label for="type" class="form-label">Type</label>
        <select class="form-select" name="type">
                <option selected>Veuillez choisir un type</option>
                <option value="Appartement">Appartement</option>
                <option value="Maison">Maison</option>
                <option value="Villa">Villa</option>
                <option value="Magasin">Magasin</option>
                <option value="Terrain">Terrain</option>
         </select> </div>

        <div class="mb-3">
        <label for="ville" class="form-label">Ville</label>
        <input type="text" class="form-control" id="ville" name="ville">
        </div>

        <div class="mb-3">
        <label for="superficie" class="form-label">Superficie</label>
        <input type="text" class="form-control" id="superficie" name="superficie">
        </div>

        <div class="mb-3 form-check-inline">
        <label class="form-label ">Etat</label><br>
         <input type="radio" id="neuf" name="neuf" value="1">Neuf &nbsp;
         <input type="radio" id="neuf" name="neuf"value='0'> Ancien
        </div>

        <div class="mb-3">
        <label for="prix" class="form-label">Prix</label>
        <input type="text" class="form-control" id="prix" name="prix">
        </div>

        <!-- <div class="mb-3">
        <label for="photo" class="form-label">photo</label>
        <input type="file" class="form-control" id="photo" name="photo">
        </div> -->

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
@endsection

resources/views/annonces/edit.blade.php
@extends("templates.master")
@section("titre", "Modifier annonce")
@section("contenu")
@isset($annonce)
      <h1 class="mt-2 mb-2">Modifier l'annonce numéro {{ $annonce->id }} </h1>   
    {{-- errors area --}}
    @if($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li> {{$error}} </li>
            @endforeach
        </ul>
    </div>
    @endif
    <form method="post" action="{{ route('annonce.update', $annonce->id )}}"  class="w-50">
        @csrf
        @method("PUT")
        <div class="mb-3">
        <label for="titre" class="form-label">Titre</label>
        <input type="text" class="form-control" id="titre" name="titre" value="{{ $annonce->titre }}">
        </div>

        <div class="mb-3">
        <label for="description" class="form-label">Description</label>
        <input type="text" class="form-control" id="description" name="description" value="{{ $annonce->description }}" >
        </div>

    
      
        <div class="mb-3">
        <label for="type" class="form-label">Type</label>
        <select class="form-select" name="type">
                <option value="Appartement"  {{ $annonce->type=="Appartement"? "selected" : "" }} >Appartement</option>
                <option value="Maison"  {{ $annonce->type=="Maison"? "selected" : "" }}>Maison</option>
                <option value="Villa"  {{ $annonce->type=="Villa"? "selected" : "" }}>Villa</option>
                <option value="Magasin"  {{ $annonce->type=="Magasin"? "selected" : "" }}>Magasin</option>
                <option value="Terrain"  {{ $annonce->type=="Terrain"? "selected" : "" }}>Terrain</option>
         </select> </div>

        <div class="mb-3">
        <label for="ville" class="form-label">Ville</label>
        <input type="text" class="form-control" id="ville" name="ville"  value="{{ $annonce->ville }}">
        </div>

        <div class="mb-3">
        <label for="superficie" class="form-label">Superficie</label>
        <input type="text" class="form-control" id="superficie" name="superficie"  value="{{ $annonce->superficie }}">
        </div>

        <div class="mb-3 form-check-inline">
        <label class="form-label ">Etat</label><br>
         <input type="radio" id="neuf" name="neuf" value="1"   {{ $annonce->neuf? "checked" : "" }}>Neuf &nbsp;
         <input type="radio" id="neuf" name="neuf"value='0' {{ $annonce->neuf? "" : "checked" }}> Ancien
        </div>

        <div class="mb-3">
        <label for="prix" class="form-label">Prix</label>
        <input type="text" class="form-control" id="prix" name="prix"  value="{{ $annonce->prix }}">
        </div>

        <!-- <div class="mb-3">
        <label for="photo" class="form-label">photo</label>
        <input type="file" class="form-control" id="photo" name="photo">
        </div> -->

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
@endisset
@endsection

resources/views/annonces/index.blade.php
@extends("templates.master")
@section("titre", "Liste des annonces")
@section("contenu")
<h2>Liste des annonces</h2>
<br>
    @if(session()->has("success"))
    <div class="alert alert-success">
        {{session("success")}}
    </div>
    @endif

<a href="{{ route('annonce.create') }}" class="btn btn-primary">Nouvelle annonce</a>
    @isset($annonces)
        <table class="table">
            <tr>
                <th>#</th>
                <th>Titre</th>
                <th>Description</th>
                <th>Type</th>
                <th>Ville</th>
                <th>Superficie (m<sup>2</sup>) </th>
                <th>Etat</th>
                <th>Prix</th>
                <th>Action</th>
            </tr>
            @foreach($annonces as $annonce)
            <tr>
                <td>{{ $annonce->id }}</td>
                <td>{{ $annonce->titre }}</td>
                <td>{{ $annonce->description }}</td>
                <td>{{ $annonce->type}}</td>
                <td>{{ $annonce->ville}}</td>
                <td>{{ $annonce->superficie}}</td>
                <td>{{ $annonce->neuf? "Neuf":"Ancien" }}</td>
                <td>{{ $annonce->prix }}</td>
                <td>
                    <form action="{{ route('annonce.destroy', $annonce->id )}}" method="post">
                         @csrf
                         @method("DELETE")
                        <a href="{{route('annonce.show', $annonce->id )}}"><i class="bi bi-eye"></i></a> 
                         <a href="{{route('annonce.edit', $annonce->id )}}"><i class="bi bi-pencil"></i></a> 
                        <button type="submit" style="border:none; background-color:transparent"
                        onclick="return confirm('Voulez vous supprimer l\'annonce :  {{ $annonce->titre }}?')"
                        
                        ><i class="bi bi-trash"></i></button>
                    </form>
                </td>
            </tr>
            @endforeach
        </table>
    @endisset
@endsection

resources/views/annonces/show.blade.php
@extends("templates.master")
@isset($annonce)
        @section("titre", "Détails de l'annonce ".$annonce->titre)
    @endisset
@section("contenu")
    @isset($annonce)

            <h2 class="mt-3 mb-2">Détails de l'annonce numéro {{$annonce->id}} </h2>
            <b>Titre : </b> {{$annonce->titre}} <br>
            <b>Description : </b> {{$annonce->description}} <br>
            <b>Type : </b> {{$annonce->type}} <br>
            <b>Etat : </b> {{$annonce->neuf? "Neuf" : "Ancien"}} <br>
            <b>Superficie : </b> {{$annonce->superficie}} <br>
            <b>Prix : </b> {{$annonce->prix}} <br>
       @endisset 
@endsection

resources/views/templates/master.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@yield("titre")</title>
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    </head>
<body>
    <div class="container">
        @yield("contenu")
    </div>
    
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</body>
</html>